version: "3"
services: 
  mongodb:
    image: "mongo:latest"
    ports: 
      - "27017:27017"

  printul:
    image: "pritunl-docker"
    environment: 
      MONGODB_URI: "mongodb://mongodb:27017/pritunl"
    ports: 
      - "3000:80"